[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio

lib_deps = 
	crankyoldgit/IRremoteESP8266 @ ^2.8.6
	lsatan/SmartRC-CC1101-Driver-Lib @ ^2.5.7
	likababel/U8g2 @ ^2.35.19
	
